server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://localhost:9296

  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**