server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:9296

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000 # 1h